### ISSUE TITLE
[Suggestion] Increase default threshold for scrips

### ISSUE THREAD

**Issue by bartcorremans** [Lharz/xiv-currency-alert#11]
As of 6.2, white and purple crafters' and gatherers' scrips have a cap of 4000, up from 2000.

It would make sense to update the default threshold to match.

Thank you for your work on this fantastic plugin!

**Comment by Lharz** [comment]
Haven't noticed that, I barely never craft in the game. Thanks for the info, I'll increase the value in next release.
