### ISSUE TITLE
[Suggestion] Specific currency icon instead of sentence

### ISSUE THREAD

**Issue by cc12138030** [Lharz/xiv-currency-alert#2]
I think it'd be great to have an option to choose to display the small simple currency icon instead of "You need to spend whatever". I really like having a notification, but would much prefer a smaller pop-up. I feel like it would also be much less intrusive as well, just showing the little actual Poetics icon instead of "You need to spend your Tomestones of Poetics".

Anyway, that's my suggestion. I don't know anything about coding these types of things and whether that type of suggestion would be difficult to implement, but hopefully this is something that is easy to implement and/or something you think might be a good idea.

Thanks.

**Comment by Lharz** [comment]
Thank you for your suggestion. I was actually planning to do this, and generally improve the UI a lot later since the current UI is basically super garbage tier. Problem is that I'm very bad in UX design so it'll probably won't come early soon. Unless someone make a PR for it. :)

**Comment by Lharz** [comment]
Done in version 0.4.0.0
