### ISSUE TITLE
Alert not appearing after v9 update?

### ISSUE THREAD

**Issue by GiacomoLaw** [Lharz/xiv-currency-alert#26]
Hi all,

Getting no alert for low currencies. 

![image](https://github.com/Lharz/xiv-currency-alert/assets/9038673/33f4704c-62dc-43bf-bd18-d0bc8919b54a)

![image](https://github.com/Lharz/xiv-currency-alert/assets/9038673/809618f8-cd35-4821-ba1a-4ba67d2e845b)

Worked fine till 6.5 game update.

Thanks

**Comment by Vaylith** [comment]
Same here

**Comment by thekoalaz** [comment]
+1

**Comment by saipheblue** [comment]
same

EDIT: found out, in the new version you need to manually select all currencies you want and enable them again + check "overlay"
