### ISSUE TITLE
[Request] Stack bottom to top

### ISSUE THREAD

**Issue by gucciBane** [Lharz/xiv-currency-alert#6]
This would be great for use along the bottom of the screen.

Thanks

**Comment by Lharz** [comment]
I don't exactly get what you mean. Do you suggest that the list should sort elements by descending currency amount ?

**Comment by Lharz** [comment]
Okay, will do that in a future version. Thanks for the suggestion !

**Comment by Lharz** [comment]
Just FYI, I tried to do it for the upcoming version but haven't found anything to make it work. I'm still leaving this up in case I find something.

**Comment by gucciBane** [comment]
Thanks for the update + for trying!
