### ISSUE TITLE
[Request] Add a command to toggle alerts window display

### ISSUE THREAD

**Issue by Hiroa** [Lharz/xiv-currency-alert#7]
Can you please, add a command to toggle the display of the alerts window ?

**Comment by Lharz** [comment]
This is doable, but... The whole point of the plugin is to display an alert, why would you want to hide it ?

**Comment by Hiroa** [comment]
I use macro to hide some part of my UI and plugins during duties. 
An other way to do that could be to add an option to automatically hide the alerts during duty

**Comment by Lharz** [comment]
I see, makes more sense to me now.

**Comment by ImRingo** [comment]
I would like to second the notion of having something togglable within the settings for the plugin that hides the UI element of the plugin while within duties. Once I am in the duty, I do not need some UI thing to tell me I need to spend my poetics. I'm in the instance, what am I going to do, leave it and get a penalty just to spend tomes? No.
