### ISSUE TITLE
Update to Dalamud 7.0

### ISSUE THREAD

**Issue by lilyremigia** [Lharz/xiv-currency-alert#9]

**Comment by jtabox** [comment]
Waiting patiently until it's updated of course, but I think I've capped multiple currencies multiple times during this time 🤣  This is one of those addons that offer huge QoL that you don't notice until it's gone and then you realize how much helpful it's been.

**Comment by Lharz** [comment]
I'm releasing an updated version very soon in testing mode as I'm not playing the game atm and can't test it myself.

Sorry for being late at the party :/

**Comment by reiichi001** [comment]
@Lharz lmk if you need any help with [DalamudPluginsD17](https://github.com/goatcorp/DalamudPluginsD17)! I've been testing using a local build, which has been working well afaik, and can help get you setup on the new plugin build system.

**Comment by Lharz** [comment]
Will check that later in the day. Thanks for the information. :)
